language: ruby

before_script: "./script/ci/before.sh"

rvm:
  - 1.9.2
  - 1.9.3

env:
  - DB=postgres

script:
  - RAILS_ENV=test bundle exec rake db:migrate spec --trace

notifications:
  email:
    - jeremyleesmith@gmail.com
